apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-api-secrets
  namespace: klaut-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hcp-vault
    kind: ClusterSecretStore
  target:
    name: vault-api-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: saas/vault-api/prod
