apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent-swarm
resources:
  - namespace.yaml
  - configmap.yaml
  - dashboard-deployment.yaml
  - async-swarm-deployment.yaml
  - services.yaml
