apiVersion: v1
kind: Service
metadata:
  name: obsevia-duca-demo
  namespace: obsevia-ducah-staging
  labels:
    app: obsevia-duca-demo
spec:
  type: ClusterIP
  selector:
    app: obsevia-duca-demo
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: obsevia-duca-demo-nodeport
  namespace: obsevia-ducah-staging
  labels:
    app: obsevia-duca-demo
spec:
  type: NodePort
  selector:
    app: obsevia-duca-demo
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30583
