apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependency-track-postgres-data
  labels:
    app: dependency-track-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
