apiVersion: v1
kind: Service
metadata:
  name: dependency-track-postgres
  labels:
    app: dependency-track-postgres
spec:
  type: ClusterIP
  selector:
    app: dependency-track-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
