apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: obsevia-duca-demo
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector/kubernetes.io~1hostname
        value: engine
