apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: search-api-secrets
  namespace: search-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: homelab-vault
    kind: ClusterSecretStore
  target:
    name: search-api-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: saas/search-api/prod
