apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-backups
  labels:
    app: supabase-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
