apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    app: kong
spec:
  type: NodePort
  selector:
    app: kong
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30480
