# Local reference only — real secret is created by scripts/k8s-supabase-secret.sh
apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: replace-me
  JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
  ANON_KEY: replace-me
  SERVICE_ROLE_KEY: replace-me
  DASHBOARD_USERNAME: supabase
  DASHBOARD_PASSWORD: replace-me
  SECRET_KEY_BASE: replace-me
  PG_META_CRYPTO_KEY: replace-me
  VAULT_ENC_KEY: replace-me
  LOGFLARE_PUBLIC_ACCESS_TOKEN: replace-me
  LOGFLARE_PRIVATE_ACCESS_TOKEN: replace-me
