apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-config
  labels:
    app: gitlab-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
