# Local reference only — real secret is created by scripts/k8s-gitlab-secret.sh
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
type: Opaque
stringData:
  GITLAB_ROOT_PASSWORD: "change-me"
  GITLAB_RUNNER_REGISTRATION_TOKEN: "change-me"
  GITLAB_URL: "http://gitlab.gitlab.svc.cluster.local"
  GITLAB_NAMESPACE: "gitlab"
  omnibus.rb: |
    external_url 'http://127.0.0.1:30481'
    gitlab_rails['initial_shared_runners_registration_token'] = 'change-me'
