apiVersion: v1
kind: Service
metadata:
  name: obsevia-chat-frontend
  namespace: obsevia-chat-staging
  labels:
    app: obsevia-chat-frontend
spec:
  type: ClusterIP
  selector:
    app: obsevia-chat-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: obsevia-chat-frontend-nodeport
  namespace: obsevia-chat-staging
  labels:
    app: obsevia-chat-frontend
spec:
  type: NodePort
  selector:
    app: obsevia-chat-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30581
