apiVersion: v1
kind: Service
metadata:
  name: step-ca
  labels:
    app: step-ca
spec:
  type: NodePort
  selector:
    app: step-ca
  ports:
    - name: https
      port: 9000
      targetPort: https
      nodePort: 30484
      protocol: TCP
